### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by mahmoudalsaman** [Execut3/django-bigbluebutton#1]
when open meeting page at admin I have this error
![Screenshot from 2020-09-22 19-22-42](https://user-images.githubusercontent.com/10051801/93915968-1958bb80-fd09-11ea-92df-8cc8c92c6333.png)

**Comment by Execut3** [comment]
did u defined your bigblue button configs.

you should define two main variables in your settings.py file. like below

BBB_API_URL = 'https://test.com/bigbluebutton/api/'
BBB_SECRET_KEY = 'abcde.......'

**Comment by Execut3** [comment]
An exception handler added, please pull and check if it's ok now.

**Comment by mahmoudalsaman** [comment]
ok now
