### ISSUE TITLE
python-bigbluebutton2

### ISSUE THREAD

**Issue by Natureshadow** [Execut3/django-bigbluebutton#2]
Hi,

just a note to check whether you are aware of https://edugit.org/infrablue/python-bigbluebutton2

If you weren't and think we should join forces, you are welcome.

Cheers,
Nik

**Comment by Execut3** [comment]
Hi, Thanks for sharing the link. But the purpose of this package is just to focus on Django. 
Also, this package is created as a loosly coupled application so anyone can install and use it. no difficult config needed. 
But If you want I can help with extending features of your package too.

**Comment by Natureshadow** [comment]
>Also, this package is created as a loosly coupled application so anyone can install and use it. no difficult config needed. 

I see no difference there. From looking at the code, the projects are mostly identical. Yours also contains a full-blown BBB client library besides the Django part. python-bigbluebutton2 does not require "difficult config" either.

**Comment by Execut3** [comment]
thanks but I prefer to keep developing packages on GitHub rather than Gitlab. But will try to help with your package too. 
Appreciate your attention

**Comment by peylight** [comment]
Hey @Execut3! Natureshadow is a [Debian Developer](https://nm.debian.org/person/natureshadow/). Wanna help him for packaging stuff?!

**Comment by Execut3** [comment]
will be glad to help :)
